# Generated by Django 2.2.1 on 2019-05-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=2000)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
